name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build
        # Save the 'dist' folder path as an output
        id: build
        env:
          DIST_PATH: dist
        # The following line sets the output variable
        # that can be accessed by other jobs
        continue-on-error: true

      - name: Check if /dist was build
        run: |
          if [ ! -d "dist" ]; then
            echo "Folder 'dist' does not exist"
            exit 1
          fi
      - name: Add CNAME File
        run: touch ./dist/CNAME && echo "swap-slovenia.com" > ./dist/CNAME

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@main
      - name: Copy 'dist' folder from build job
        run: cp -r ${{ needs.build.outputs.dist_path }} dist
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
