name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Push git subdirectory as branch
        # You may pin to the exact commit or the version.
        # uses: s0/git-publish-subdir-action@92faf786f11dfa44fc366ac3eb274d193ca1af7e
        uses: s0/git-publish-subdir-action@v2.6.0 

      - name: Build with Vite
        run: npm run build

      # Deploy to another repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:owner/repo.git
          BRANCH: gh-pages
          FOLDER: dist
